/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.umss.view;

/**
 *
 * @author gorge
 */
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuprincipal
     */
    public menuPrincipal() {
        initComponents();
        this.setExtendedState(menuPrincipal.MAXIMIZED_BOTH);  // maximiza la pantalla
        this.setTitle("Gestor de ensayos - UMSS"); // pone el titulo a la  ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuhome = new javax.swing.JMenu();
        mnuusuariosregistrados = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        mnuensayos = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuayuda = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnucerrarsesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principal.setBackground(java.awt.SystemColor.textHighlight);

        mnuhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/umss/img/if_Home_131778.png"))); // NOI18N
        mnuhome.setMnemonic('f');
        mnuhome.setText("Home");
        menuBar.add(mnuhome);

        mnuusuariosregistrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/umss/img/if_Work_area_131767.png"))); // NOI18N
        mnuusuariosregistrados.setMnemonic('e');
        mnuusuariosregistrados.setText("Usuarios registrados");

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/umss/img/if_Designer_131853.png"))); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Comision Revisora");
        mnuusuariosregistrados.add(cutMenuItem);

        pasteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        pasteMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/umss/img/verde-usuario-icono-8942-32.png"))); // NOI18N
        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Investigadores");
        mnuusuariosregistrados.add(pasteMenuItem);

        menuBar.add(mnuusuariosregistrados);

        mnuensayos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/umss/img/if_Color_profile_131910.png"))); // NOI18N
        mnuensayos.setMnemonic('h');
        mnuensayos.setText("Ensayos");

        contentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/umss/img/if_To_do_list_131719.png"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Aceptados");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        mnuensayos.add(contentMenuItem);

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/umss/img/copiar-los-archivos-de-documentos-de-icono-7129-32.png"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Rechazados");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        mnuensayos.add(aboutMenuItem);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/umss/img/busqueda-de-archivos-de-documentos-zoom-vista-previa-de-icono-4373-32.png"))); // NOI18N
        jMenuItem1.setText("Observados");
        mnuensayos.add(jMenuItem1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/umss/img/documentos-de-hdd-icono-7371-32.png"))); // NOI18N
        jMenuItem4.setText("SubirEnsayo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuensayos.add(jMenuItem4);
        jMenuItem4.getAccessibleContext().setAccessibleDescription("");

        menuBar.add(mnuensayos);

        mnuayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/umss/img/if_Warning_131773.png"))); // NOI18N
        mnuayuda.setText("Ayuda");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/umss/img/ayuda-a-un-punto-de-consulta-de-icono-8396-32.png"))); // NOI18N
        jMenuItem2.setText("Acerca de");
        mnuayuda.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/umss/img/ayuda-de-beos-icono-9566-32.png"))); // NOI18N
        jMenuItem3.setText("Ayuda");
        mnuayuda.add(jMenuItem3);

        menuBar.add(mnuayuda);

        mnucerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/umss/img/cierre-de-sesion-icono-4342-32.png"))); // NOI18N
        mnucerrarsesion.setText("Cerrar Sesion");
        menuBar.add(mnucerrarsesion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        ListaComisionRevisora obj = new ListaComisionRevisora();
        obj.setVisible(true);
        
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        subirEnsayo obj = new subirEnsayo();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuayuda;
    private javax.swing.JMenu mnucerrarsesion;
    private javax.swing.JMenu mnuensayos;
    private javax.swing.JMenu mnuhome;
    private javax.swing.JMenu mnuusuariosregistrados;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JDesktopPane principal;
    // End of variables declaration//GEN-END:variables

}
